In [2]:
print ("hello this ready")

hello this ready

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("✓ All libraries loaded!")

✓ All libraries loaded!

In [11]:
!pip install plotly

Requirement already satisfied: plotly in /opt/anaconda3/envs/wine-rec/lib/python3.10/site-packages (6.5.2)
Requirement already satisfied: narwhals>=1.15.1 in /opt/anaconda3/envs/wine-rec/lib/python3.10/site-packages (from plotly) (2.16.0)
Requirement already satisfied: packaging in /opt/anaconda3/envs/wine-rec/lib/python3.10/site-packages (from plotly) (25.0)

In [43]:
df = pd.read_csv('../data/raw/winemag-data-130k-v2.csv')
df

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [42]:
df.sample(10)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
61709,61709,US,"Tense and full-bodied, Summit is from all Cale...",Quail Hill Vineyard Summit,93,70.0,California,Russian River Valley,Sonoma,Virginie Boone,@vboone,Lynmar 2012 Quail Hill Vineyard Summit Pinot N...,Pinot Noir,Lynmar
102239,102239,Austria,A touch of black cherry with the faintest lick...,Steinberg,93,39.0,Burgenland,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Jalits 2014 Steinberg Red (Burgenland),Austrian Red Blend,Jalits
64285,64285,US,There's something vegetal on this Zin that low...,Salvador Vineyard,84,38.0,California,Contra Costa County,Central Coast,NaN,NaN,Turley 2010 Salvador Vineyard Zinfandel (Contr...,Zinfandel,Turley
1670,1670,France,This is a seriously wood-aged wine. Its burnt ...,NaN,85,28.0,Bordeaux,Saint-Émilion,NaN,Roger Voss,@vossroger,Château Pindefleurs 2013 Saint-Émilion,Bordeaux-style Red Blend,Château Pindefleurs
83458,83458,US,"Year in and year out, Dolce is one of Californ...",Late Harvest,95,85.0,California,Napa Valley,Napa,NaN,NaN,Dolce 2005 Late Harvest Semillon-Sauvignon Bla...,Semillon-Sauvignon Blanc,Dolce
61615,61615,Spain,"This fresh, pure value red cranks out raspberr...",Roble,90,13.0,Northern Spain,Bierzo,NaN,Michael Schachner,@wineschach,Encanto 2011 Roble Mencía (Bierzo),Mencía,Encanto
103608,103608,US,This wine still seems to be in its shell with ...,Dead Horse,91,55.0,Washington,Red Mountain,Columbia Valley,Sean P. Sullivan,@wawinereport,Mark Ryan 2012 Dead Horse Cabernet Sauvignon (...,Cabernet Sauvignon,Mark Ryan
85249,85249,US,"A light, straightforward and focused wine, 100...",Estate Grown,90,38.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Cuvaison 2013 Estate Grown Pinot Noir (Napa Va...,Pinot Noir,Cuvaison
7916,7916,Australia,Representative of the solid values that may be...,Catapult,90,20.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Wirra Wirra 2012 Catapult Shiraz (McLaren Vale),Shiraz,Wirra Wirra
57573,57573,US,There is a marvelous intensity from the first ...,Temperance Hill Vineyard,93,75.0,Oregon,Eola-Amity Hills,Willamette Valley,Paul Gregutt,@paulgwine,Adelsheim 2012 Temperance Hill Vineyard Pinot ...,Pinot Noir,Adelsheim

Observations: 
1. Remove unnamed columns, taster name, taste twitter handle, region2
2. Province are there for most of them, but region information is missing for some
3. Need to clean title, description
4. Potentially remove designation since we already have winery given
5. Clean title, description, country, province, region1, and veriety

In [49]:
# Drop some columns
# inplace = True means the dataFrame is modified in place
#df.drop(["Unnamed: 0", "taster_name", "taster_twitter_handle", "region_2"], axis=1, inplace=True)
df

,country,description,designation,points,price,province,region_1,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit